# Generated by Django 2.2.7 on 2019-12-04 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191204_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='profile/%Y/%m/%d/', verbose_name='Profile Photo')),
                ('prefix', models.CharField(choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.'), ('Mis', 'Miss.'), ('Mx', 'Mx.'), ('Dr', 'Dr.'), ('Prf', 'Prof.'), ('Rv', 'Rev.')], max_length=5, verbose_name='Prefix')),
                ('firstname', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('cellphone', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('company', models.CharField(blank=True, max_length=200, null='True', verbose_name='Company Name')),
                ('website', models.URLField(verbose_name='Website Url')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
