# Generated by Django 2.2.7 on 2020-01-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191210_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magnauser',
            name='mobile',
        ),
    ]
