# Generated by Django 2.2.7 on 2019-12-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profilep.jpg', max_length=200, upload_to='profile/%Y/%m/%d/', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank='True', null='True', verbose_name='Website Url'),
        ),
    ]
