# Generated by Django 2.2.7 on 2019-12-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191204_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='magnauser',
            name='mobile',
            field=models.CharField(default=1, max_length=20, verbose_name='Mobile Number'),
            preserve_default=False,
        ),
    ]
