# Generated by Django 2.2.7 on 2019-12-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_magnauser_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magnauser',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email Adddress'),
        ),
    ]
