# Generated by Django 2.2.7 on 2019-12-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191206_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magnauser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email Adddress'),
        ),
    ]
