# Generated by Django 2.2.7 on 2020-01-31 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('ABA', 'Auto, Boat & Air'), ('BP', 'Business & Professional'), ('CC', 'Charity & Causes'), ('CoC', 'Community & Culture'), ('FE', 'Family & Education'), ('FB', 'Fashion & Beauty'), ('FME', 'Film , Media & Entertainment'), ('FD', 'Food & Drink'), ('GP', 'Government & Politics'), ('HW', 'Health & Wellness'), ('HSI', 'Hobbies & Special Interest'), ('HL', 'Home & Lifestyle'), ('M', 'Music'), ('PVA', 'Performing & Visual Arts'), ('RS', 'Religion & Spirituality'), ('SA', 'School Activities'), ('ST', 'Science & Technology'), ('SH', 'Seasonal & Holiday'), ('SF', 'Sports & Fitness'), ('TO', 'Travel & Outdoor'), ('Other', 'Other')], max_length=10, verbose_name='Event Category')),
                ('name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('description', models.CharField(blank=True, max_length=50000, null=True, verbose_name='Event Description')),
                ('venue', models.CharField(max_length=255, verbose_name='Venue')),
                ('start_date', models.DateField(verbose_name='Event Start Date')),
                ('start_time', models.CharField(max_length=10, verbose_name='Start Time')),
                ('end_date', models.DateField(verbose_name='Event End Date')),
                ('end_time', models.CharField(max_length=10, verbose_name='End Time')),
                ('time_zone', models.CharField(max_length=255, verbose_name='Event Timezone')),
                ('image', models.ImageField(default='profilep.jpg', upload_to='event/%Y/%m/%d/')),
                ('payout', models.CharField(blank=True, choices=[('MTN', 'MTN Mobile Money'), ('Bank', 'Bank Deposit'), ('Voda', 'Vodafone Cash')], max_length=10, null=True, verbose_name='Event Payout Method')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Event')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Guest Email Addrress')),
            ],
        ),
        migrations.CreateModel(
            name='GuestList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guest List Name')),
            ],
        ),
        migrations.CreateModel(
            name='GuestTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Ticket Count')),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Organizer Name')),
                ('logo', models.ImageField(default='profilep.jpg', upload_to='organizer/%Y/%m/%d/')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website Url')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook Url')),
                ('twitter', models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter Url')),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram  Url')),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True, verbose_name='LinkedIn Url')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('p', 'Paid'), ('f', 'Free')], max_length=1, verbose_name='Ticket Type')),
                ('name', models.CharField(max_length=50, verbose_name='Ticket Name')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ticket Price')),
                ('description', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Ticket Description')),
                ('minimum_ticket_order', models.PositiveIntegerField(default='1', verbose_name='Minimum Order')),
                ('maximum_ticket_order', models.PositiveIntegerField(verbose_name='Maximum Order')),
                ('sales_channel', models.CharField(blank=True, choices=[('on', 'Online only'), ('door', 'At the door only'), ('both', 'Everywhere')], max_length=5, null=True, verbose_name='Ticket Sales Channel')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
