# Generated by Django 2.2.7 on 2019-12-04 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Organizer Name')),
                ('logo', models.ImageField(upload_to='organizer/%Y/%m/%d/')),
                ('description', models.CharField(max_length=255, verbose_name='Organizer Description')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website Url')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook Url')),
                ('twitter', models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter Url')),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram  Url')),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True, verbose_name='LinkedIn Url')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ABA', 'Auto, Boat & Air'), ('BP', 'Business & Professional'), ('CC', 'Charity & Causes'), ('CoC', 'Community & Culture'), ('FE', 'Family & Education'), ('FB', 'Fashion & Beauty'), ('FME', 'Film , Media & Entertainment'), ('FD', 'Food & Drink'), ('GP', 'Government & Politics'), ('HW', 'Health & Wellness'), ('HSI', 'Hobbies & Special Interest'), ('HL', 'Home & Lifestyle'), ('M', 'Music'), ('PVA', 'Performing & Visual Arts'), ('RS', 'Religion & Spirituality'), ('SA', 'School Activities'), ('ST', 'Science & Technology'), ('SH', 'Seasonal & Holiday'), ('SF', 'Sports & Fitness'), ('TO', 'Travel & Outdoor'), ('Other', 'Other')], max_length=10, verbose_name='Event Category')),
                ('name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('description', models.CharField(max_length=255, verbose_name='Event Description')),
                ('venue', models.CharField(max_length=255, verbose_name='Venue')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Event Start Date')),
                ('start_time', models.CharField(max_length=10, verbose_name='Start Time')),
                ('end_date', models.DateField(auto_now_add=True, verbose_name='Event End Date')),
                ('end_time', models.CharField(max_length=10, verbose_name='End Time')),
                ('time_zone', models.CharField(max_length=255, verbose_name='Event Timezone')),
                ('organiszer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Organizer')),
            ],
        ),
    ]
