# Generated by Django 2.2.7 on 2019-12-10 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.UUID('6b286b7e-1e26-4301-8453-d77261d4ec65'), editable=False, unique=True, verbose_name='Event Id')),
                ('category', models.CharField(choices=[('ABA', 'Auto, Boat & Air'), ('BP', 'Business & Professional'), ('CC', 'Charity & Causes'), ('CoC', 'Community & Culture'), ('FE', 'Family & Education'), ('FB', 'Fashion & Beauty'), ('FME', 'Film , Media & Entertainment'), ('FD', 'Food & Drink'), ('GP', 'Government & Politics'), ('HW', 'Health & Wellness'), ('HSI', 'Hobbies & Special Interest'), ('HL', 'Home & Lifestyle'), ('M', 'Music'), ('PVA', 'Performing & Visual Arts'), ('RS', 'Religion & Spirituality'), ('SA', 'School Activities'), ('ST', 'Science & Technology'), ('SH', 'Seasonal & Holiday'), ('SF', 'Sports & Fitness'), ('TO', 'Travel & Outdoor'), ('Other', 'Other')], max_length=10, verbose_name='Event Category')),
                ('name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('description', models.CharField(max_length=255, verbose_name='Event Description')),
                ('venue', models.CharField(max_length=255, verbose_name='Venue')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Event Start Date')),
                ('start_time', models.CharField(max_length=10, verbose_name='Start Time')),
                ('end_date', models.DateField(auto_now_add=True, verbose_name='Event End Date')),
                ('end_time', models.CharField(max_length=10, verbose_name='End Time')),
                ('time_zone', models.CharField(max_length=255, verbose_name='Event Timezone')),
                ('image', models.ImageField(default='profilep.jpg', upload_to='event/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Guest Email Addrress')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('p', 'Paid'), ('f', 'Free')], max_length=1, verbose_name='Event Type')),
                ('name', models.CharField(max_length=50, verbose_name='Ticket Name')),
                ('quantity', models.CharField(max_length=30, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ticket Price')),
                ('sale_start_date', models.DateField(auto_now_add=True, verbose_name='Event Start Date')),
                ('sale_start_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='Start Time')),
                ('sale_end_date', models.DateField(auto_now_add=True, verbose_name='Event End Date')),
                ('sale_end_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='End Time')),
                ('description', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Event Description')),
                ('visibility', models.CharField(blank=True, choices=[('v', 'visible'), ('h', 'hidden')], max_length=1, null=True, verbose_name='Event Type')),
                ('minimum_ticket_order', models.PositiveSmallIntegerField(default='1', verbose_name='Minimum Order')),
                ('maximum_ticket_order', models.PositiveIntegerField(verbose_name='Maximum Order')),
                ('sales_channel', models.CharField(blank=True, choices=[('on', 'Online only'), ('door', 'At the door only'), ('both', 'Everywhere')], max_length=5, null=True, verbose_name='Ticket Sales Channel')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Organizer Name')),
                ('logo', models.ImageField(default='profilep.jpg', upload_to='organizer/%Y/%m/%d/')),
                ('description', models.CharField(max_length=255, verbose_name='Organizer Description')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website Url')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook Url')),
                ('twitter', models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter Url')),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram  Url')),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True, verbose_name='LinkedIn Url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuestTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Ticket Count')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Guest')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='GuestList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guest List Name')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='guest_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.GuestList'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Organizer'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
