# Generated by Django 2.2.7 on 2019-12-10 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('81458004-3851-41a9-9aca-802eb7c9e5fc'), editable=False, unique=True, verbose_name='Event Id'),
        ),
    ]
