# Generated by Django 2.2.7 on 2020-01-31 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='guestticket',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Guest'),
        ),
        migrations.AddField(
            model_name='guestticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Ticket'),
        ),
        migrations.AddField(
            model_name='guestlist',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='guestlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guest',
            name='guest_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.GuestList'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Organizer'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
