# Generated by Django 2.2.7 on 2019-12-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191204_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organiszer',
            new_name='organizer',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='profilep.jpg', upload_to='event/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='logo',
            field=models.ImageField(default='profilep.jpg', upload_to='organizer/%Y/%m/%d/'),
        ),
    ]
