# Generated by Django 2.2.7 on 2019-12-10 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191210_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('e63daedb-c831-4ec1-a3d9-65c7907d3b6d'), editable=False, unique=True, verbose_name='Event Id'),
        ),
    ]
