# Generated by Django 2.2.6 on 2019-12-16 19:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20191210_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Event Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('1c36ae06-c8a8-4be7-a2a3-b21a345ae832'), editable=False, unique=True, verbose_name='Event Id'),
        ),
    ]
