# Generated by Django 2.2.7 on 2020-01-31 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200131_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time_zone',
        ),
    ]
