# Generated by Django 2.2.7 on 2019-12-06 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20191204_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('p', 'Paid'), ('f', 'Free')], max_length=1, verbose_name='Event Type')),
                ('name', models.CharField(max_length=50, verbose_name='Ticket Name')),
                ('quantity', models.CharField(max_length=30, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ticket Price')),
                ('sale_start_date', models.DateField(auto_now_add=True, verbose_name='Event Start Date')),
                ('sale_start_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='Start Time')),
                ('sale_end_date', models.DateField(auto_now_add=True, verbose_name='Event End Date')),
                ('sale_end_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='End Time')),
                ('description', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Event Description')),
                ('visibility', models.CharField(blank=True, choices=[('v', 'visible'), ('h', 'hidden')], max_length=1, null=True, verbose_name='Event Type')),
                ('minimum_ticket_order', models.PositiveSmallIntegerField(default='1', verbose_name='Minimum Order')),
                ('maximum_ticket_order', models.PositiveIntegerField(verbose_name='Maximum Order')),
                ('sales_channel', models.CharField(blank=True, choices=[('on', 'Online only'), ('door', 'At the door only'), ('both', 'Everywhere')], max_length=5, null=True, verbose_name='Ticket Sales Channel')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
