# Generated by Django 2.2.6 on 2019-12-16 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20191216_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(verbose_name='Event End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('b2e4f9d9-33b2-4238-b11f-27363a936052'), editable=False, unique=True, verbose_name='Event Id'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(verbose_name='Event Start Date'),
        ),
    ]
