# Generated by Django 2.2.7 on 2019-12-19 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20191216_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=1, max_length=100, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('5a2fbb08-4167-47dc-868c-d24e3b209343'), editable=False, unique=True, verbose_name='Event Id'),
        ),
    ]
