# Generated by Django 2.2.7 on 2019-12-19 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20191219_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('340796bd-22dc-4252-9aad-984e5ddc6ebc'), editable=False, unique=True, verbose_name='Event Id'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
