# Generated by Django 2.2.7 on 2020-02-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200131_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sales_channel',
            field=models.CharField(blank=True, choices=[('Online only', 'Online only'), ('At the door', 'At the door only'), ('Everywhere', 'Everywhere')], max_length=50, null=True, verbose_name='Ticket Sales Channel'),
        ),
    ]
