# Generated by Django 2.2.7 on 2019-12-24 00:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20191219_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('c5fa6094-44b7-4729-a084-349348e5a4c7'), editable=False, unique=True, verbose_name='Event Id'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
