# Generated by Django 2.2.7 on 2020-02-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='maximum_ticket_order',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='minimum_ticket_order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
