# Generated by Django 2.2.7 on 2019-12-24 09:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20191224_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('5233458b-6c69-473a-83a0-7255bb904085'), editable=False, unique=True, verbose_name='Event Id'),
        ),
    ]
