# Generated by Django 2.2.7 on 2020-02-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200201_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='original.jpg', upload_to='event/%Y/%m/%d/'),
        ),
    ]
