# Generated by Django 2.2.7 on 2020-01-15 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20191224_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('4f8685f4-6cef-4f1e-812e-27e6adbbb402'), editable=False, unique=True, verbose_name='Event Id'),
        ),
    ]
