# Generated by Django 2.2.7 on 2020-01-21 20:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200115_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('287e9c5e-96f7-455f-aada-d9b71d4e226d'), editable=False, unique=True, verbose_name='Event Id'),
        ),
    ]
