# Generated by Django 2.2.7 on 2020-02-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200201_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_order',
            field=models.BooleanField(default=False, verbose_name='Hidden Event'),
        ),
    ]
