# Generated by Django 2.2.7 on 2020-02-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_has_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(choices=[('GHS', 'GHS'), ('NGN', 'NGN')], default='GHS', max_length=50, verbose_name='Event Currency'),
        ),
    ]
