# Generated by Django 2.2.7 on 2020-01-21 20:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20200121_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('c50af0aa-0b2b-46ce-a162-fa6c20a1df10'), editable=False, unique=True, verbose_name='Event Id'),
        ),
    ]
