# Generated by Django 2.2.7 on 2020-01-22 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20200121_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('c5ae26b6-a63d-4364-bdd8-169444e39495'), editable=False, unique=True, verbose_name='Event Id'),
        ),
    ]
