# Generated by Django 2.2.10 on 2020-02-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='max_order',
            field=models.PositiveIntegerField(default=10, verbose_name='Maximum Order'),
        ),
    ]
