# Generated by Django 2.2.7 on 2020-01-22 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20200122_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('9fe7fd32-2c8a-4115-8f93-7c300b38f5cc'), editable=False, unique=True, verbose_name='Event Id'),
        ),
    ]
