# Generated by Django 2.2.7 on 2020-01-22 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20200122_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('e29d7ea6-6ec0-46dc-837e-da6141992ff3'), editable=False, unique=True, verbose_name='Event Id'),
        ),
    ]
