# Generated by Django 2.2.7 on 2020-01-22 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20200122_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('725ee6dc-f743-4e0a-850f-f04201393001'), editable=False, unique=True, verbose_name='Event Id'),
        ),
    ]
