# Generated by Django 2.2.7 on 2020-01-23 20:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20200122_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='visibility',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('4bf51af1-dd0a-4736-8606-8f5189e193b4'), editable=False, unique=True, verbose_name='Event Id'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='kind',
            field=models.CharField(choices=[('p', 'Paid'), ('f', 'Free')], max_length=1, verbose_name='Ticket Type'),
        ),
    ]
