# Generated by Django 2.2.7 on 2020-01-23 21:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20200123_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('70e0eb72-5a9a-4007-9519-2605ae978ae8'), editable=False, unique=True, verbose_name='Event Id'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Ticket Description'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
    ]
