# Generated by Django 2.2.7 on 2020-01-23 21:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20200123_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='sale_end_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sale_end_time',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sale_start_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sale_start_time',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('b26e2ccd-84dd-478e-a4a7-cd8995ec4ebf'), editable=False, unique=True, verbose_name='Event Id'),
        ),
    ]
