# Generated by Django 2.2.7 on 2020-01-23 21:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20200123_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('cf5e1355-09cc-4b3a-a6e9-d6c4eeb59c23'), editable=False, unique=True, verbose_name='Event Id'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='maximum_ticket_order',
            field=models.CharField(max_length=10, verbose_name='Maximum Order'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='minimum_ticket_order',
            field=models.CharField(default='1', max_length=10, verbose_name='Minimum Order'),
        ),
    ]
