# Generated by Django 2.2.7 on 2020-01-23 21:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20200123_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('8b10bffc-bf71-49c2-89ea-ca3ee6c38d63'), editable=False, unique=True, verbose_name='Event Id'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='maximum_ticket_order',
            field=models.PositiveIntegerField(verbose_name='Maximum Order'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='minimum_ticket_order',
            field=models.PositiveIntegerField(default='1', verbose_name='Minimum Order'),
        ),
    ]
