# Generated by Django 2.2.7 on 2020-01-25 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20200123_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('fc3beef3-a531-44fc-9e3e-ca2243dcf7b9'), editable=False, unique=True, verbose_name='Event Id'),
        ),
    ]
