# Generated by Django 2.2.7 on 2020-01-25 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20200125_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payout',
            field=models.CharField(blank=True, choices=[('MTN', 'MTN Mobile Money'), ('Bank', 'Bank Deposit'), ('Voda', 'Vodafone Cash')], max_length=10, null=True, verbose_name='Event Payout Method'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('261daea5-aff9-4073-8141-277260dc1b09'), editable=False, unique=True, verbose_name='Event Id'),
        ),
    ]
