# Generated by Django 2.2.7 on 2020-01-25 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20200125_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('4828d02e-f127-4102-93e5-17aaffd51a13'), editable=False, unique=True, verbose_name='Event Id'),
        ),
    ]
