# Generated by Django 2.2.7 on 2020-01-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20200125_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_id',
        ),
    ]
