# Generated by Django 2.2.7 on 2020-01-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_remove_event_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=50000, null=True, verbose_name='Event Description'),
        ),
    ]
